[package]
name = "cw-orch-daemon"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "../README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[features]
default = ["node-tests"]
# enable node-backed tests (ensure Docker is running)
# run with `cargo test --jobs 1 --features node-tests`
node-tests = []
eth = ["dep:ethers-signers", "dep:ethers-core"]
[dependencies]
# Default deps
cw-orch-contract-derive = { workspace = true }
cw-orch-fns-derive = { workspace = true }
cw-orch-core = { workspace = true }
cw-orch-networks = { workspace = true }

cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
schemars = "0.8.10"
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

# Daemon deps
sha256 = { workspace = true }
ibc-relayer-types = { workspace = true }
prost = { version = "0.12" }
bitcoin = { version = "0.30.0" }
hex = { version = "0.4.3" }
ripemd = { version = "0.1.3" }
ibc-chain-registry = { workspace = true }
tokio = { version = "1.4", features = ["full"] }
tonic = { version = "0.9.2", features = ["tls", "tls-roots"] }
secp256k1 = { version = "0.27.0", default-features = false }
reqwest = { version = "0.11.9" }
base64 = { version = "0.21.0" }
hkd32 = { version = "0.7.0", features = ["bip39", "mnemonic", "bech32"] }
rand_core = { version = "0.6.4", default-features = false }
ed25519-dalek = { version = "2", features = ["serde"] }
eyre = { version = "0.6" }
cosmrs = { version = "0.14.0", features = ["dev", "cosmwasm", "grpc"] }
chrono = { version = "0.4" }
base16 = { version = "0.2.1" }
derive_builder = { version = "0.12.0" }
ring = { version = "0.16.20" }

# Injective dependencies
ethers-signers = { version = "2.0.7", optional = true }
ethers-core = { version = "2.0.7", optional = true }

[dev-dependencies]
cw-orch-daemon = { path = "." }
uid = "0.1.7"
env_logger = "0.10.0"
cw20 = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cw20-base = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cosmwasm-schema = "1.2"
tokio-test = "0.4.2"
speculoos = "0.11.0"
ctor = "0.2.0"
duct = "0.13"
counter-contract = { path = "../contracts/counter", features = ["interface"] }
mock-contract = { path = "../contracts/mock_contract", features = [
  "interface",
] }
mock-contract-u64 = { path = "../contracts/mock_contract_u64", features = [
  "interface",
] }
serial_test = "2.0.0"

# Ethereum deps
ethers-signers = { version = "2.0.7" }
ethers-core = { version = "2.0.7" }
